module.exports = {
  apps: [
    {
      name: 'whatsapp-bot',
      script: 'bot.js',
      cwd: 'E:/Projetos/Central-Notificacoes/whatsapp-bot',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
    },
    {
      name: 'webhook-whatsapp',
      script: 'server2.js',
      cwd: 'C:/Projetos/WebhookWhatsAppNode',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
    },
    {
      name: 'portal-consultas',
      script: 'app.js',
      cwd: 'C:/Projetos/PortalConsultasCini',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
    },
    {
      name: 'whatsapp-motoristas',
      script: 'server.js',
      cwd: 'E:/Projetos/Central-Notificacoes/WhatsAppMotoristas',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
    },
    {
      name: 'whatsapp-webnode',
      script: 'server2.js',
      cwd: 'E:/Projetos/Central-Notificacoes/WhatsAppWebNode',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
    },
    {
      name: 'client-baixas-pix',
      script: 'C:/Users/nerias.sousa/AppData/Local/Programs/Python/Python312/python.exe',
      args: '-u app.py',
      cwd: 'C:/Projetos/ClientBaixasPIX',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/ClientBaixasPIX/logs/client-baixas-pix.log',
      error_file: 'C:/Projetos/ClientBaixasPIX/logs/client-baixas-pix.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },
    {
      name: 'portal-streamlit',
      script: 'C:/Users/nerias.sousa/AppData/Local/Programs/Python/Python312/Scripts/streamlit.exe',
      args: 'run app.py',
      cwd: 'C:/Projetos/PortalConsultasStreamlit',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/PortalConsultasStreamlit/logs/portal-streamlit.log',
      error_file: 'C:/Projetos/PortalConsultasStreamlit/logs/portal-streamlit.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },
    {
      name: 'gerenciador-cargas',
      script: 'C:/Projetos/gerenciador-cargas/venv/Scripts/python.exe',
      args: '-u manage.py runserver 0.0.0.0:8502',
      cwd: 'C:/Projetos/gerenciador-cargas',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/gerenciador-cargas/logs/gerenciador-cargas.log',
      error_file: 'C:/Projetos/gerenciador-cargas/logs/gerenciador-cargas-error.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },    {
      name: 'central-notificacoes',
      script: 'C:/Users/nerias.sousa/AppData/Local/Programs/Python/Python312/python.exe',
      args: '-u central_notificacoes.py',
      cwd: 'E:/Projetos/Central-Notificacoes/CentralNotificacoes',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Central-Notificacoes/CentralNotificacoes/logs/central-notificacoes.log',
      error_file: 'E:/Projetos/Central-Notificacoes/CentralNotificacoes/logs/central-notificacoes.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },  ],
};
