module.exports = {
  apps: [
    {
      name: 'whatsapp-bot',
      script: 'bot.js',
      cwd: 'E:/Projetos/Central-Notificacoes/whatsapp-bot',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Central-Notificacoes/whatsapp-bot/logs/whatsapp-bot.log',
      error_file: 'E:/Projetos/Central-Notificacoes/whatsapp-bot/logs/whatsapp-bot.log',
      merge_logs: true,
    },
    {
      name: 'webhook-whatsapp',
      script: 'server2.js',
      cwd: 'C:/Projetos/WebhookWhatsAppNode',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/WebhookWhatsAppNode/logs/pm2-out.log',
      error_file: 'C:/Projetos/WebhookWhatsAppNode/logs/pm2-error.log',
      merge_logs: true,
    },
    {
      name: 'portal-consultas',
      script: 'app.js',
      cwd: 'C:/Projetos/PortalConsultasCini',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/PortalConsultasCini/logs/portal-consultas.log',
      error_file: 'C:/Projetos/PortalConsultasCini/logs/portal-consultas.log',
      merge_logs: true,
    },
    {
      name: 'whatsapp-motoristas',
      script: 'server.js',
      cwd: 'E:/Projetos/Central-Notificacoes/WhatsAppMotoristas',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Central-Notificacoes/WhatsAppMotoristas/logs/whatsapp-motoristas.log',
      error_file: 'E:/Projetos/Central-Notificacoes/WhatsAppMotoristas/logs/whatsapp-motoristas.log',
      merge_logs: true,
    },
    {
      name: 'whatsapp-webnode',
      script: 'server2.js',
      cwd: 'E:/Projetos/Central-Notificacoes/WhatsAppWebNode',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Central-Notificacoes/WhatsAppWebNode/logs/whatsapp-webnode.log',
      error_file: 'E:/Projetos/Central-Notificacoes/WhatsAppWebNode/logs/whatsapp-webnode.log',
      merge_logs: true,
    },
    {
      name: 'client-baixas-pix',
      script: 'C:/Users/nerias.sousa/AppData/Local/Programs/Python/Python312/python.exe',
      args: '-u app.py',
      cwd: 'C:/Projetos/ClientBaixasPIX',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/ClientBaixasPIX/logs/client-baixas-pix.log',
      error_file: 'C:/Projetos/ClientBaixasPIX/logs/client-baixas-pix.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },
    {
      name: 'portal-streamlit',
      script: 'C:/Users/nerias.sousa/AppData/Local/Programs/Python/Python312/Scripts/streamlit.exe',
      args: 'run app.py --server.port 8501',
      cwd: 'C:/Projetos/PortalConsultasStreamlit',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/PortalConsultasStreamlit/logs/portal-streamlit.log',
      error_file: 'C:/Projetos/PortalConsultasStreamlit/logs/portal-streamlit.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },
    {
      name: 'gerenciador-cargas',
      script: 'C:/Projetos/gerenciador-cargas/venv/Scripts/python.exe',
      args: '-u manage.py runserver 0.0.0.0:8502 --noreload',
      cwd: 'C:/Projetos/gerenciador-cargas',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/gerenciador-cargas/logs/gerenciador-cargas.log',
      error_file: 'C:/Projetos/gerenciador-cargas/logs/gerenciador-cargas-error.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },
    {
      name: 'central-notificacoes',
      script: 'C:/Users/nerias.sousa/AppData/Local/Programs/Python/Python312/python.exe',
      args: '-u central_notificacoes.py',
      cwd: 'E:/Projetos/Central-Notificacoes/CentralNotificacoes',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Central-Notificacoes/CentralNotificacoes/logs/central-notificacoes.log',
      error_file: 'E:/Projetos/Central-Notificacoes/CentralNotificacoes/logs/central-notificacoes.log',
      merge_logs: true,
      env: { PYTHONIOENCODING: 'utf-8', PYTHONUNBUFFERED: '1' },
    },
    {
      name: 'portal-vagas-rh',
      script: 'app.js',
      cwd: 'E:/Projetos/PortalVagasRH',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/PortalVagasRH/logs/portal-vagas-rh.log',
      error_file: 'E:/Projetos/PortalVagasRH/logs/portal-vagas-rh.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3020 },
    },
    {
      name: 'portal-api',
      script: 'server.js',
      cwd: 'E:/Projetos/portalApi',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/portalApi/logs/portal-api.log',
      error_file: 'E:/Projetos/portalApi/logs/portal-api.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3014 },
    },
    {
      name: 'cini-dashboard',
      script: 'server.js',
      cwd: 'E:/Projetos/CiniManager/dashboard',
      exec_mode: 'cluster',
      instances: 'max',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/CiniManager/dashboard/logs/pm2-out.log',
      error_file: 'E:/Projetos/CiniManager/dashboard/logs/pm2-error.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3000 },
    },
    // ── Aplicações incorporadas ao ecossistema ──────────────────────────────
    {
      name: 'api-sicredi',
      script: 'src/app.js',
      cwd: 'E:/Projetos/API_Sicredi',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/API_Sicredi/logs/api-sicredi.log',
      error_file: 'E:/Projetos/API_Sicredi/logs/api-sicredi.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3012 },
    },
    {
      name: 'api-weduu',
      script: 'src/server.js',
      cwd: 'C:/Projetos/API_Weduu',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/API_Weduu/logs/api-weduu.log',
      error_file: 'C:/Projetos/API_Weduu/logs/api-weduu.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT_WEDUU: 3004 },
    },
    {
      name: 'central-tarefas',
      script: 'server.js',
      cwd: 'E:/Projetos/Central_Tarefas',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Central_Tarefas/logs/central-tarefas.log',
      error_file: 'E:/Projetos/Central_Tarefas/logs/central-tarefas.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3011 },
    },
    {
      name: 'cini-pricing',
      script: 'server.js',
      cwd: 'E:/Projetos/Cini-Pricing',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Cini-Pricing/logs/cini-pricing.log',
      error_file: 'E:/Projetos/Cini-Pricing/logs/cini-pricing.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3009 },
    },
    {
      name: 'erp-cini',
      script: 'server.js',
      cwd: 'E:/Projetos/Gestao_Portaria/erp_cini',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Gestao_Portaria/erp_cini/logs/erp-cini.log',
      error_file: 'E:/Projetos/Gestao_Portaria/erp_cini/logs/erp-cini.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3003 },
    },
    {
      name: 'hub-cini',
      script: 'server.js',
      cwd: 'E:/Projetos/Hub_Cini',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/Hub_Cini/logs/hub-cini.log',
      error_file: 'E:/Projetos/Hub_Cini/logs/hub-cini.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3005 },
    },
    {
      name: 'notificador-pix',
      script: 'app.js',
      cwd: 'C:/Projetos/Confirmacao_Pix/NotificadorPIX',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'C:/Projetos/Confirmacao_Pix/NotificadorPIX/logs/notificador-pix.log',
      error_file: 'C:/Projetos/Confirmacao_Pix/NotificadorPIX/logs/notificador-pix.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3013 },
    },
    {
      name: 'wf-cini',
      script: 'server.js',
      cwd: 'E:/Projetos/WF_Cini/wf_cini',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/WF_Cini/wf_cini/logs/wf-cini.log',
      error_file: 'E:/Projetos/WF_Cini/wf_cini/logs/wf-cini.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3008 },
    },
    {
      name: 'portal-ete',
      script: 'app.js',
      cwd: 'E:/Projetos/portalETE',
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      out_file: 'E:/Projetos/portalETE/logs/portal-ete.log',
      error_file: 'E:/Projetos/portalETE/logs/portal-ete.log',
      merge_logs: true,
      env: { NODE_ENV: 'production', PORT: 3021 },
    },
  ],
};
