/*
  Banco alvo: usar o mesmo banco/config do ERP Cini (.env)
  - servidor: DB_SERVER_ERP
  - usuario: DB_USER_ERP
  - senha: DB_PASSWORD_ERP
  - database: DB_DATABASE_DW (normalmente 'dw')
*/

IF OBJECT_ID('dbo.CINI_MANAGER_GRUPOS_APPS', 'U') IS NOT NULL
BEGIN
  DROP TABLE dbo.CINI_MANAGER_GRUPOS_APPS;
END;
GO

IF OBJECT_ID('dbo.CINI_MANAGER_GRUPOS', 'U') IS NOT NULL
BEGIN
  DROP TABLE dbo.CINI_MANAGER_GRUPOS;
END;
GO

CREATE TABLE dbo.CINI_MANAGER_GRUPOS (
  ID_GRUPO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  NOME_GRUPO NVARCHAR(120) NOT NULL,
  ATIVO BIT NOT NULL CONSTRAINT DF_CINI_MANAGER_GRUPOS_ATIVO DEFAULT (1),
  DTINC DATETIME NOT NULL CONSTRAINT DF_CINI_MANAGER_GRUPOS_DTINC DEFAULT (GETDATE())
);
GO

CREATE UNIQUE INDEX UX_CINI_MANAGER_GRUPOS_NOME_ATIVO
  ON dbo.CINI_MANAGER_GRUPOS (NOME_GRUPO)
  WHERE ATIVO = 1;
GO

CREATE TABLE dbo.CINI_MANAGER_GRUPOS_APPS (
  ID_GRUPO INT NOT NULL,
  APP_NAME NVARCHAR(120) NOT NULL,
  ORDEM INT NOT NULL CONSTRAINT DF_CINI_MANAGER_GRUPOS_APPS_ORDEM DEFAULT (1),
  DTINC DATETIME NOT NULL CONSTRAINT DF_CINI_MANAGER_GRUPOS_APPS_DTINC DEFAULT (GETDATE()),
  CONSTRAINT PK_CINI_MANAGER_GRUPOS_APPS PRIMARY KEY (ID_GRUPO, APP_NAME),
  CONSTRAINT FK_CINI_MANAGER_GRUPOS_APPS_GRUPO
    FOREIGN KEY (ID_GRUPO) REFERENCES dbo.CINI_MANAGER_GRUPOS (ID_GRUPO)
);
GO

CREATE INDEX IX_CINI_MANAGER_GRUPOS_APPS_ORDEM
  ON dbo.CINI_MANAGER_GRUPOS_APPS (ID_GRUPO, ORDEM);
GO
